spring:
  application:
    name: workguard-api
  cloud:
    gcp:
      project-id: ${GCP_PROJECT_ID:workguard-506815}
      storage:
        enabled: false
  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY:AIzaSyDummyKeyForStartup}
        chat:
          options:
            model: gemini-3.7-flash

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

server:
  port: ${PORT:8080}
